{{- $root := . -}}
{{- range $name, $svc := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  replicas: {{ $svc.replicas | default $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: "{{ $.Values.image.repository }}/{{ $name }}:{{ $.Values.image.tag }}"
        ports:
        - containerPort: {{ $svc.port }}
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ $svc.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ $svc.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
---
{{- end }}
