# Generic deployment template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.repository }}/{{ .Values.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.port }}
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.port }}
          initialDelaySeconds: 15
          periodSeconds: 20
