name: CI Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build services
        run: |
          for d in user-service appointment-service inventory-service billing-service auth-service notification-service; do
            (cd $d && ./gradlew clean build -x test) || exit 1
          done
